version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    conex-generator:
      image: deephdc/deep-oc-conex-generator
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    conex-generator-gpu:
      image: deephdc/deep-oc-conex-generator:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    conex-generator-rclone:
      extends:
        service: conex-generator
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
